export ZSH=$HOME/.zsh

# History
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

# Starship
eval "$(starship init zsh)"

# fnm
FNM_PATH="/home/$USER/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="/home/$USER/.local/share/fnm:$PATH"
  eval "`fnm env`"
fi

eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"

# Autocompletion
zmodload zsh/complist
autoload -U compinit
compinit


#-- Debug
# git
# export GIT_TRACE=1
# QT
# export QT_DEBUG_PLUGINS=1

[[ -f $ZSH/plugins/plugins.zsh ]] && source $ZSH/plugins/plugins.zsh
[[ -f $ZSH/aliases.zsh ]] && source $ZSH/aliases.zsh

zstyle ':completion:*' menu select # selectable menu
zstyle ':completion:*' matcher-list 'm:{[:lowe:][:uper:]-_}={[:upper:][:lower:]-_}' 'r:|=*' 'l:|=* r:|=*' # case insensitive completion
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:kill:*processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01' # colorize kill list

export PINENTRY_KDE_USE_WALLET=1

GPG_TTY=$(readlink /proc/$$/fd/2)
export GPG_TTY
export LIBVIRT_DEFAULT_URI="qemu:///system"

PATH=~/.console-ninja/.bin:$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/jhair/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/jhair/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/jhair/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/jhair/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Android SDK
export ANDROID_HOME=$HOME/Android/Sdk 
export PATH=$PATH:$ANDROID_HOME/emulator 
export PATH=$PATH:$ANDROID_HOME/platform-tools

# CUDA
export PATH="/opt/cuda/bin:$PATH"
export CUDA_HOME="/opt/cuda"

# CONDA
export PATH="/home/$USER/miniconda3/bin:$PATH"